-> in: throw_exception() in test_simple_logger
<- out: throw_exception()
*******************************************************************************************
Exception: Everything is awflu!!?
*******************************************************************************************
